### ISSUE TITLE
Can I use two email addresses for MFA using custom policies?

### ISSUE THREAD

**Issue by 1993Saurabh** [marcelodiiorio/My-Azure-AD-B2C-use-cases#1]
Hi @marcelodiiorio ,

I would just like to know, can we use two email addresses for Multi-factor authentication in custom policies just like two phone numbers. Is it possible to do that?

Any help would be appreciated in this regard.

**Comment by marcelodiiorio** [comment]
Hello @1993Saurabh. I think that you are talking about using Alternate Email Address. This is not available in B2C, like in Azure AD.

**Comment by 1993Saurabh** [comment]
> Hello @1993Saurabh. I think that you are talking about using Alternate Email Address. This is not available in B2C, like in Azure AD.

Hi @marcelodiiorio ,

Thanks for the response.

Are you sure that it is not available as of now in ADB2C?

**Comment by marcelodiiorio** [comment]
Hi @1993Saurabh except I'm missing something, yes. That's the latest information I have. Let me double check just in case.

**Comment by 1993Saurabh** [comment]
@marcelodiiorio if possible could you please provide some official statement or link. It would be really helpful.

**Comment by marcelodiiorio** [comment]
I think that [this](https://stackoverflow.com/questions/42207627/azure-ad-b2c-password-reset-policy-with-alternate-email-address) explains why it should not be something available in B2C. It's a response where people from the product group is involved.

**Comment by 1993Saurabh** [comment]
> I think that [this](https://stackoverflow.com/questions/42207627/azure-ad-b2c-password-reset-policy-with-alternate-email-address) explains why it should not be something available in B2C. It's a response where people from the product group is involved.

Hi @marcelodiiorio ,

Thanks a lot for providing the reference.
